config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'faq' => 'pages#faq'
  get 'help' => 'pages#help'

  root 'pages#home'

  resources :notes
  devise_for :teachers
  resources :games
  resources :students
  resources :categories do
    member do
      patch 'update_title'
    end
  end
  resources :questions

  get 'class_gameplay/:id/home' => 'class_gameplay#home', as: :class_gameplay

  get 'student_gameplay/login'
  post 'student_gameplay/login'
  get 'student_gameplay/logout'
  get 'student_gameplay/:id/home/:group_id' =>'student_gameplay#home', as: :student_gameplay

  get 'teacher_gameplay/:id/current_group/:group_id' => 'teacher_gameplay#current_group', as: :current_group
  get 'teacher_gameplay/:id/home' => 'teacher_gameplay#home', as: :teacher_gameplay
  post 'teacher_gameplay/:id/home' => 'teacher_gameplay#home'
  patch 'teacher_gameplay/:id/update_score/:group_id' => 'teacher_gameplay#update_score', as: :update_score
  get 'teacher_gameplay/:id/edit_score/:group_id' => 'teacher_gameplay#edit_score', as: :edit_score
  patch 'teacher_gameplay/:id/next_group' => 'teacher_gameplay#next_group', as: :next_group
  get 'teacher_gameplay/:id/active/:student_id' => 'teacher_gameplay#active', as: :active
  patch 'teacher_gameplay/:id/next_question/:question_id/:group_id' => 'teacher_gameplay#next_question', as: :next_question
  post 'teacher_gameplay/:id/send_message/:group_id' => 'teacher_gameplay#send_message', as: :send_message

  get 'game_sessions/:game_id/new' => 'game_sessions#new', as: :new_game_session
  post 'game_sessions/:game_id/create' => 'game_sessions#create', as: :create_game_session
  get 'game_sessions/:id/groups' => 'game_sessions#groups', as: :game_session_groups
  delete 'game_sessions/:id/destroy' => 'game_sessions#destroy', as: :delete_game_session
  patch 'game_sessions/:id/assign_groups' => 'game_sessions#assign_groups', as: :assign_groups
  post 'game_sessions/:id/add_player/:group_id/:student_id' => 'game_sessions#add_player', as: :add_player
  patch 'game_sessions/:id/end_game' => 'game_sessions#end_game', as: :end_game
  patch 'game_sessions/:id/update_map' => 'game_sessions#update_map'
  get 'game_sessions/:id/add_group' => 'game_sessions#add_group'
  patch 'game_sessions/:id/update' => 'game_sessions#update', as: :update_game_session
  get 'game_sessions/:id/edit' => 'game_sessions#edit', as: :edit_game_session

  post 'supplies/:id/create/:group_id' => 'supplies#create', as: :supply
  get 'supplies/:id/edit/:supply_id' => 'supplies#edit', as: :edit_supply
  patch 'supplies/:id/update/:supply_id' => 'supplies#update', as: :update_supply
  delete 'supplies/:id/destroy/:supply_id' => 'supplies#destroy', as: :delete_supply

end

app/controllers/teacher_gameplay_controller.rb
class TeacherGameplayController < ApplicationController
  before_action :set_game_session

  def home
    @current_group = @game_session.this_groups_turn
    @question = @game_session.random_question
  end

  def group_links
    @game_session
  end

  def current_group
    @current_group = Group.find(params[:group_id])
    @supply = Supply.new
    respond_to do |format|
      format.js
    end
  end

  def edit_score
    @current_group = Group.find(params[:group_id])
    respond_to do |format|
      format.js
    end
  end

  def update_score
    @game_session
    @current_group = Group.find(params[:group_id])
    respond_to do |format|
      if @current_group.update(group_params)
        format.js
      else
        format.html { render :home, notice: 'Score failed to be updated.' }
      end
    end
    WebsocketRails[:"group_listen#{@current_group.game_session_id}"].trigger 'update_score', @current_group
  end

  def next_group
    if @game_session.update(game_session_params)
      @current_group = @game_session.this_groups_turn
      @supply = Supply.new
      @question = @game_session.random_question
      respond_to do |format|
        format.js
      end
    else
      render :home, notice: "Try Again"
    end
    turn_group_name = Group.find(@game_session.turn_group_id).name
    WebsocketRails[:"group_listen#{@game_session.id}"].trigger 'turn_display', turn_group_name
  end

  def active
    @assignment = GroupAssignment.joins("INNER JOIN groups ON groups.id = group_assignments.group_id and group_assignments.student_id = #{params[:student_id]} and groups.game_session_id = #{params[:id]}").last
    if @assignment.active == true
      @assignment.update(active: false)
    else
      @assignment.update(active: true)
    end

    respond_to do |format|
      format.js
    end
    WebsocketRails[:"group_listen#{params[:id]}"].trigger 'icon_display', @assignment
    active_list
  end

  def next_question
    @question = Question.find(params[:question_id])
    if params[:question]
      @question.update(question_params)
      if params[:question][:right]
        group = Group.find(params[:group_id])
        @question.give_points(group)
        WebsocketRails[:"group_listen#{group.game_session_id}"].trigger 'update_score', group
      end
    end
    @current_group = @game_session.this_groups_turn
    @question = @game_session.random_question

    respond_to do |format|
      format.js
    end
  end

  def send_message
    @message = params[:message_text]
    @current_group = Group.find(params[:group_id])
    respond_to do |format|
      format.js
    end
    WebsocketRails[:"question_listen#{params[:group_id]}"].trigger 'send_message', @message
  end

  private def set_game_session
    @game_session = GameSession.find(params[:id])
  end

  private def group_params
    params.require(:group).permit(:score)
  end

  private def game_session_params
    params.require(:game_session).permit(:turn_group_id, :name, :winning_group_id)
  end

  private def supply_params
    params.require(:supply).permit(:group_id, :name, :amount)
  end

  private def question_params
    params.require(:question).permit(:right, :wrong)
  end

  private def active_list
    group_list = []
    group = Group.find(@assignment.group_id)
    group.students.order(:last_name).each do |student|
      group_list << "#{student.active?(group.id)} #{student.full_name}"
    end
    WebsocketRails[:"question_listen#{group.id}"].trigger 'group_list', group_list
  end

end

app/helpers/teacher_gameplay_helper.rb
module TeacherGameplayHelper
end

app/views/teacher_gameplay/_answer_buttons.html.erb
<div id="answerButtonsModal" class="modal">
  <div class="modal-fg">
    <button type="button" id="close-answer-buttons" class="close-modal button-margin"><i class="fa fa-times"></i></button>

    <div id="correct">
      <%= simple_form_for @question, url: next_question_path(@game_session, @question, @current_group.id), remote: true do |f| %>
        <%= f.hidden_field :right, value: f.object.right + 1%>
        <%= f.button :submit, "Correct", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect", id: "button-correct" %>
      <% end %>
    </div>

    <div id="incorrect">
      <%= simple_form_for @question, url: next_question_path(@game_session, @question, @current_group.id), remote: true do |f| %>
        <%= f.hidden_field :wrong, value: f.object.wrong + 1 %>
        <%= f.button :submit, "Incorrect", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect", id: "button-incorrect" %>
      <% end %>
    </div>
  </div>
</div>

app/views/teacher_gameplay/_current_group.html.erb
<div class="current-group" id="<%= @current_group.id %>">
  <h3>
    <%= "#{@current_group.this_turn?}".html_safe %>
    <%= "#{@current_group.name}: " %>
    <span id="update_score<%= @current_group.id %>" class="scores">
      <%= render partial: '/teacher_gameplay/scores' %>
    </span>
  </h3>
  <%= "It is currently this group's turn." if @current_group.group_turn?%><br>
  <button id="send-message" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored button-margin">
    Send Message
  </button>
</div>

<div class="supplies">
  <h5>Supplies
    <button type="button" class="add-button" id="addSupplies">
      <i class="fa fa-plus"></i> ADD
    </button>
  </h5>
  <ul>
    <% if @current_group.supplies.length == 0 %>
      <li>
        No Supplies Added
      </li>
    <% else %>
      <% @current_group.supplies.each do |s| %>
        <li><div id="s<%= s.id %>"><%= render partial: '/supplies/show', locals: { s: s } %></div></li>
      <% end %>
    <% end %>
  </ul>
</div>


<div id="notes<%= @current_group.id %>">
  <%= render partial: '/notes/index', locals: { group: @current_group } %>
</div>


<div id="send-message-container">
  <%= render partial: '/teacher_gameplay/send_message', locals: { group: @current_group } %>
</div>

app/views/teacher_gameplay/_edit_score_form.html.erb
<%= simple_form_for @current_group, url: update_score_path(@game_session, @current_group), remote: true do |f| %>

  <%= f.input :score, label: false, wrapper_html: { class: "mdl-textfield mdl-js-textfield textfield-demo edit-score-container" }, input_html: { class: "mdl-textfield__input" }, label_html: { class: "mdl-textfield__label" } %>

  <%= f.button :submit, "Update", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>

<% end %>

app/views/teacher_gameplay/_group_links.html.erb
<ul>
<% @game_session.groups.order(:id).each do |group| %>
  <li class="group-link" id="group<%= group.id %>"><%= link_to "#{group.this_turn?} #{group.name} #{group.score}".html_safe, current_group_path(@game_session.id,group.id), remote: true %></li>
<% end %>
</ul>

app/views/teacher_gameplay/_modals.html.erb
<div class="modal" id="suppliesModal">
  <div class="modal-fg mdl-cell--3-col">
    <h2>
      <%= render partial: '/supplies/form', locals: { id: @current_group.id, supply: Supply.new } %>
    </h2>
    <button class="close-modal mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Close</button>
  </div>
</div>

<div id="notesModal" class="modal">
  <div class="modal-fg modal-card mdl-cell--3-col">
    <%= render partial: '/notes/form', locals: { id: @current_group.id, note: Note.new } %>
    <button class="close-modal mdl-button mdl-js-button mdl-button--raised mdl-button--colored button-margin">Close</button>
  </div>
</div>

<div id="sendMessageModal" class="modal">
  <div class="modal-fg">
    <%= form_tag send_message_path(@game_session, @current_group), remote: true, :class => "mdl-grid" do %>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo mdl-cell mdl-cell--6-col">
        <%= text_area_tag :message_text, nil, class: "mdl-textfield__input", placeholder: "Enter Message Here" %>
      </div>

      <div class="input">
        <%= submit_tag 'Send', class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
      </div>
    <% end %>
    <button class="close-modal mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Close</button>
  </div>
</div>

app/views/teacher_gameplay/_next_question.html.erb
<h3>
  Next Question
  <%= link_to "Skip This Question", next_question_path(@game_session, @question, @current_group), class: "skip-question button", method: :patch, remote: true %>
</h3>

<div class="question-content">
  <h4><%= @question.content %></h4>
</div>

<div>
  <h5>Answer: <%= @question.answer %></h5>
</div>

<div>
  <div class="mdl-cell mdl-cell--2-col"></div>
  <div class="btn-group" id="group-choices">
    <% @game_session.groups.each do |group| %>
      <div>
        <% if group == @game_session.this_groups_turn %>
          <input class="box" id="box<%= group.id %>" type="checkbox" value="<%= group.id %>" autocomplete="off" checked disabled=true>
        <% else %>
          <input class="box" id="box<%= group.id %>" type="checkbox" value="<%= group.id %>" autocomplete="off">
        <% end %>
        <label><%= group.name %></label>
      </div>
    <% end %>
  </div>
</div>

<div>
  <%= simple_form_for @question, url: next_question_path(@game_session, @question, @current_group.id), html: { id: 'competition-question-form', remote: true} do |f| %>
    <%= f.hidden_field :right, value: f.object.right + 1%>
  <% end %>
</div>

app/views/teacher_gameplay/_next_turn.html.erb
<%= simple_form_for @game_session, url: next_group_path(@game_session), remote: true  do |f| %>
  <%= f.hidden_field :turn_group_id, value: @game_session.next_group %>
  <%= f.button :submit, "Next Turn", class: "next-turn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored button-margin" %>
<% end %>

app/views/teacher_gameplay/active.js.erb
$('#roster').html("<%= j(render partial: 'roster') %>");

app/views/teacher_gameplay/current_group.js.erb
$('#current-group').html("<%= j(render partial: 'current_group', locals: { current_group: @current_group}) %>");
$('#modals').html("<%= j(render partial: 'modals') %>");

app/views/teacher_gameplay/edit_score.js.erb
$('#update_score<%= @current_group.id %>').html("<%= j(render partial: 'edit_score_form') %>");

app/views/teacher_gameplay/home.html.erb
<div class="mdl-cell mdl-cell--12-col">
  <div id="game-header">
    <%= @game_session.name %>
  </div>
  <span class="link">
    <%= link_to "Projector View", class_gameplay_path(@game_session), class: "mdl-button mdl-js-button mdl-button--accent button" %>
  </span>
</div>

<div class="column-1">
  <div id="group-links">
    <%= render partial: 'group_links' %>
  </div>
  <div id="next-turn">
    <%= render partial: '/teacher_gameplay/next_turn' %>
  </div>
</div>

<div class="column-2">
  <div id="current-group">
    <%= render partial: 'current_group' %>
  </div>
</div>

<div class="column-3">
  <div id="next-question">
    <%= render partial: 'next_question' %>
  </div>
  <div>
    <button id="send-question" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
      Send Question
    </button>
  </div>
  <div>
    <ul
      id="list-competition-answers">
    </ul>
  </div>
  <div id="roster">
    <%= render partial: 'roster' %>
  </div>
</div>



<div id="answer-buttons">
  <%= render partial: 'answer_buttons' %>
</div>

<div id="modals"><%= render partial: 'modals' %></div>

app/views/teacher_gameplay/next_question.js.erb
$('#answer-buttons').html("<%= j(render partial: 'answer_buttons') %>")
$('#next-question').html("<%= j(render partial: 'next_question') %>");
$('#list-competition-answers').empty();
$('#group-links').html("<%= j(render partial: 'group_links') %>");
$('#group<%= @current_group.id %>').addClass('active-group');
$('#current-group').html("<%= j(render partial: 'current_group', locals: { current_group: @current_group}) %>");

app/views/teacher_gameplay/send_message.js.erb
$("#sendMessageModal").toggleClass('active');
$('#sendMessageModal').find('textarea')[0].value = ''