config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'faq' => 'pages#faq'
  get 'help' => 'pages#help'

  root 'pages#home'

  resources :notes
  devise_for :teachers
  resources :games
  resources :students
  resources :categories do
    member do
      patch 'update_title'
    end
  end
  resources :questions

  get 'class_gameplay/:id/home' => 'class_gameplay#home', as: :class_gameplay

  get 'student_gameplay/login'
  post 'student_gameplay/login'
  get 'student_gameplay/logout'
  get 'student_gameplay/:id/home/:group_id' =>'student_gameplay#home', as: :student_gameplay

  get 'teacher_gameplay/:id/current_group/:group_id' => 'teacher_gameplay#current_group', as: :current_group
  get 'teacher_gameplay/:id/home' => 'teacher_gameplay#home', as: :teacher_gameplay
  post 'teacher_gameplay/:id/home' => 'teacher_gameplay#home'
  patch 'teacher_gameplay/:id/update_score/:group_id' => 'teacher_gameplay#update_score', as: :update_score
  get 'teacher_gameplay/:id/edit_score/:group_id' => 'teacher_gameplay#edit_score', as: :edit_score
  patch 'teacher_gameplay/:id/next_group' => 'teacher_gameplay#next_group', as: :next_group
  get 'teacher_gameplay/:id/active/:student_id' => 'teacher_gameplay#active', as: :active
  patch 'teacher_gameplay/:id/next_question/:question_id/:group_id' => 'teacher_gameplay#next_question', as: :next_question
  post 'teacher_gameplay/:id/send_message/:group_id' => 'teacher_gameplay#send_message', as: :send_message

  get 'game_sessions/:game_id/new' => 'game_sessions#new', as: :new_game_session
  post 'game_sessions/:game_id/create' => 'game_sessions#create', as: :create_game_session
  get 'game_sessions/:id/groups' => 'game_sessions#groups', as: :game_session_groups
  delete 'game_sessions/:id/destroy' => 'game_sessions#destroy', as: :delete_game_session
  patch 'game_sessions/:id/assign_groups' => 'game_sessions#assign_groups', as: :assign_groups
  post 'game_sessions/:id/add_player/:group_id/:student_id' => 'game_sessions#add_player', as: :add_player
  patch 'game_sessions/:id/end_game' => 'game_sessions#end_game', as: :end_game
  patch 'game_sessions/:id/update_map' => 'game_sessions#update_map'
  get 'game_sessions/:id/add_group' => 'game_sessions#add_group'
  patch 'game_sessions/:id/update' => 'game_sessions#update', as: :update_game_session
  get 'game_sessions/:id/edit' => 'game_sessions#edit', as: :edit_game_session

  post 'supplies/:id/create/:group_id' => 'supplies#create', as: :supply
  get 'supplies/:id/edit/:supply_id' => 'supplies#edit', as: :edit_supply
  patch 'supplies/:id/update/:supply_id' => 'supplies#update', as: :update_supply
  delete 'supplies/:id/destroy/:supply_id' => 'supplies#destroy', as: :delete_supply

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :maps, dependent: :destroy
  has_many :game_sessions, dependent: :destroy
  belongs_to :teacher

  validates :name, presence: true
  validates :movement, numericality: { greater_than: 0 }

  def available_game_sessions(id)
    if self.teacher_id.nil?
      GameSession.where(teacher_id: id).where(game_id: self.id)
    else
      self.game_sessions
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_teacher!

  def index
    @teacher = Teacher.find(current_teacher.id)
    @games = @teacher.available_games
  end

  def show
  end

  def new
    @game = Game.new(teacher_id: current_teacher.id)
  end

  def edit
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end


  private  def set_game
      @game = Game.find(params[:id])
  end

  private  def game_params
      params.require(:game).permit(:teacher_id, :name, :icon_id, :movement)
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<div class="mdl-cell mdl-cell--4-col"></div>
<%= simple_form_for @game, html: { class: "mdl-cell mdl-cell--4-col form-padding" } do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, wrapper_html: { class: "mdl-textfield mdl-js-textfield mdl-textfield--floating-label" }, input_html: { class: "mdl-textfield__input" }, label_html: { class: "mdl-textfield__label" } %>
  <%= f.input :movement, label: "Movement allowed per turn.", wrapper_html: { class: "mdl-textfield mdl-js-textfield mdl-textfield--floating-label" }, input_html: { class: "mdl-textfield__input" }, label_html: { class: "mdl-textfield__label" } %>

  <%= f.hidden_field :teacher_id %>

  <%= f.button :submit, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>

<% end %>
<div class="mdl-cell mdl-cell--4-col"></div>

app/views/games/_story_modal.html.erb
<div id="storyModal">
  <div class="modal-fg modal-card">
    <div><%= @game_session.game.story %></div>
    <button type="button" class="story-close mdl-button mdl-js-button mdl-button--raised mdl-button--colored button-margin" data-dismiss="modal">Close</button>
  </div>
</div>

app/views/games/edit.html.erb
<div class="mdl-cell mdl-cell--12-col center">
  <h3>Editing Game</h3>
</div>

<%= render 'form' %>

<%= link_to 'Show', @game, html_options = { class: "mdl-button mdl-js-button mdl-button--accent" } %>
<%= link_to 'New Game Scenario', new_game_path, html_options = { class: "mdl-button mdl-js-button mdl-button--accent" } %>

app/views/games/index.html.erb
<div class="mdl-cell mdl-cell--12-col center">
  <h3>Available Game Scenarios</h3>
</div>

<div class="mdl-cell mdl-cell--12-col mdl-grid game-card-container">
  <% @games.each do |game| %>
    <div class="mdl-cell mdl-cell--3-col mdl-shadow--4dp game-card">
      <div class="remove-game"><%= link_to '<i class="fa fa-times"></i>'.html_safe, game, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      <span><%= game.name %></span>
      <div class="game-container"><a href="<%= edit_game_path(game) %>"><img class="preview" src="<%= game.maps.first.file_path %>"></a></div>
      <span><%= link_to 'Start New Game', new_game_session_path(game), html_options = { class: "mdl-button mdl-js-button mdl-button--accent button", remote: true } %></span>
    </div>
  <% end %>
</div>

<div class="mdl-cell mdl-cell--12-col center">
  <h3>Games In Progress</h3>
</div>

<div class="mdl-cell mdl-cell--2-col"></div>

<table class="mdl-data-table mdl-js-data-table mdl-shadow--4dp mdl-cell mdl-cell--8-col current-games">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Name</th>
      <th class="mdl-data-table__cell--non-numeric">Player Icon</th>
      <th class="mdl-data-table__cell--non-numeric">Game</th>
      <th>Last Active Date</th>
      <th class="mdl-data-table__cell--non-numeric">Winner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <% game.available_game_sessions(@teacher.id).each do |game_session| %>
        <tr id="game<%=game_session.id%>">
          <td class="mdl-data-table__cell--non-numeric"><%= game_session.name %></td>
          <td><i class="<%= game_session.icon.description %> fa-2x"></i></td>
          <td class="mdl-data-table__cell--non-numeric"><%= game.name %></td>
          <td><%= game_session.updated_at.strftime("%b %e, %Y") %></td>
          <td class="mdl-data-table__cell--non-numeric"><%= Group.find(game_session.winning_group_id).name if game_session.winning_group_id %></td>
          <td><%= link_to 'Play', teacher_gameplay_path(game_session) %></td>
          <td><%= link_to 'Groups', game_session_groups_path(game_session) %></td>
          <td>
            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_game_session_path(game_session), html_options = {remote: true} %>
            <%= link_to '<i class="fa fa-times"></i>'.html_safe, delete_game_session_path(game_session), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="mdl-cell mdl-cell--2-col"></div>

<div id="new-game-container" class="modal">
  <div id="newGameSessionModal">
    <div class="modal-fg modal-card">
      <div id="new-game-form"></div>
      <button type="button" class="close-modal mdl-button mdl-js-button mdl-button--raised mdl-button--colored" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="mdl-cell mdl-cell--12-col center">
  <h3>New Game</h3>
</div>

<%= render 'form' %>

app/views/games/show.html.erb
<div class="mdl-cell mdl-cell--4-col"></div>
<div class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--4dp">
  <div class="mdl-card__title mdl-card--border">
    <h4>Name: <%= @game.name %></h4>
  </div>
  
  <div class="mdl-card__supporting-text">
    Movement: <%= @game.movement %>
  </div>
</div>
<div class="mdl-cell mdl-cell--4-col"></div>

<%= link_to 'Edit', edit_game_path(@game), html_options = { class: "mdl-button mdl-js-button mdl-button--accent" } %>
<%= link_to 'New Game Scenario', new_game_path, html_options = { class: "mdl-button mdl-js-button mdl-button--accent" } %>