config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'faq' => 'pages#faq'
  get 'help' => 'pages#help'

  root 'pages#home'

  resources :notes
  devise_for :teachers
  resources :games
  resources :students
  resources :categories do
    member do
      patch 'update_title'
    end
  end
  resources :questions

  get 'class_gameplay/:id/home' => 'class_gameplay#home', as: :class_gameplay

  get 'student_gameplay/login'
  post 'student_gameplay/login'
  get 'student_gameplay/logout'
  get 'student_gameplay/:id/home/:group_id' =>'student_gameplay#home', as: :student_gameplay

  get 'teacher_gameplay/:id/current_group/:group_id' => 'teacher_gameplay#current_group', as: :current_group
  get 'teacher_gameplay/:id/home' => 'teacher_gameplay#home', as: :teacher_gameplay
  post 'teacher_gameplay/:id/home' => 'teacher_gameplay#home'
  patch 'teacher_gameplay/:id/update_score/:group_id' => 'teacher_gameplay#update_score', as: :update_score
  get 'teacher_gameplay/:id/edit_score/:group_id' => 'teacher_gameplay#edit_score', as: :edit_score
  patch 'teacher_gameplay/:id/next_group' => 'teacher_gameplay#next_group', as: :next_group
  get 'teacher_gameplay/:id/active/:student_id' => 'teacher_gameplay#active', as: :active
  patch 'teacher_gameplay/:id/next_question/:question_id/:group_id' => 'teacher_gameplay#next_question', as: :next_question
  post 'teacher_gameplay/:id/send_message/:group_id' => 'teacher_gameplay#send_message', as: :send_message

  get 'game_sessions/:game_id/new' => 'game_sessions#new', as: :new_game_session
  post 'game_sessions/:game_id/create' => 'game_sessions#create', as: :create_game_session
  get 'game_sessions/:id/groups' => 'game_sessions#groups', as: :game_session_groups
  delete 'game_sessions/:id/destroy' => 'game_sessions#destroy', as: :delete_game_session
  patch 'game_sessions/:id/assign_groups' => 'game_sessions#assign_groups', as: :assign_groups
  post 'game_sessions/:id/add_player/:group_id/:student_id' => 'game_sessions#add_player', as: :add_player
  patch 'game_sessions/:id/end_game' => 'game_sessions#end_game', as: :end_game
  patch 'game_sessions/:id/update_map' => 'game_sessions#update_map'
  get 'game_sessions/:id/add_group' => 'game_sessions#add_group'
  patch 'game_sessions/:id/update' => 'game_sessions#update', as: :update_game_session
  get 'game_sessions/:id/edit' => 'game_sessions#edit', as: :edit_game_session

  post 'supplies/:id/create/:group_id' => 'supplies#create', as: :supply
  get 'supplies/:id/edit/:supply_id' => 'supplies#edit', as: :edit_supply
  patch 'supplies/:id/update/:supply_id' => 'supplies#update', as: :update_supply
  delete 'supplies/:id/destroy/:supply_id' => 'supplies#destroy', as: :delete_supply

end

app/models/supply.rb
class Supply < ActiveRecord::Base
  belongs_to :group

  validates :name, presence: true
  validates :group_id, presence: true
  validates :amount, presence: true

end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: [:edit, :update, :destroy]
  before_action :set_game_session

  def create
    @supply = Supply.new(supply_params)
    @supply.save
    @current_group = Group.find(params[:group_id])
    respond_to do |format|
      format.js
    end
    send_supplies(@current_group)
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    current_group = Group.find(@supply.group_id)
    respond_to do |format|
      if @supply.update(supply_params)
        format.js
      else
        format.html { render :groups, notice: 'Supply failed to be updated.' }
      end
    end
    send_supplies(current_group)
  end

  def destroy
    current_group = Group.find(@supply.group_id)
    @id = params[:supply_id]
    @supply.destroy
    respond_to do |format|
      format.js
    end
    send_supplies(current_group)
  end

  private def set_supply
    @supply = Supply.find(params[:supply_id])
  end

  private def set_game_session
    @game_session = GameSession.find(params[:id])
  end

  private def supply_params
    params.require(:supply).permit(:group_id, :name, :amount)
  end

  private def send_supplies(current_group)
    supplies = Supply.where(group_id: current_group.id)
    WebsocketRails[:"question_listen#{current_group.id}"].trigger 'update_supplies', supplies
  end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= simple_form_for supply, url: (supply.new_record? ? supply_path(@game_session, id) : update_supply_path(@game_session, supply)), remote: true do |f| %>
  <%= f.input :amount, label: false, placeholder: 'Amount', wrapper_html: { class: "mdl-textfield mdl-js-textfield" }, input_html: { class: "mdl-textfield__input" }, label_html: { class: "mdl-textfield__label" } %>
  <%= f.input :name, label: false, placeholder: 'Name', wrapper_html: { class: "mdl-textfield mdl-js-textfield" }, input_html: { class: "mdl-textfield__input" }, label_html: { class: "mdl-textfield__label" } %>
  <%= f.hidden_field :group_id, value: id %>
  <%= f.button :submit, "Submit", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect", id: "assignSupplies" %>
<% end %>

app/views/supplies/_show.html.erb
<%= link_to "#{s.amount} #{s.name}", edit_supply_path(@game_session, s), remote: true %>

<%= link_to '<i class="fa fa-times"></i>'.html_safe, delete_supply_path(@game_session, s), method: :delete, remote: true %>

app/views/supplies/create.js.erb
$('#current-group').html("<%= j(render partial: '/teacher_gameplay/current_group') %>");
$('#modals').html("<%= j(render partial: '/teacher_gameplay/modals') %>");

app/views/supplies/destroy.html.erb
<h1>Supplies#destroy</h1>
<p>Find me in app/views/supplies/destroy.html.erb</p>

app/views/supplies/destroy.js.erb
$("#s<%= @id %>").remove();

app/views/supplies/edit.js.erb
$("#s<%= @supply.id %>").html("<%= j(render partial: '/supplies/form', locals: { supply: @supply, id: @supply.group.id }) %>");

app/views/supplies/update.js.erb
$("#s<%= @supply.id %>").html("<%= j(render partial: 'show', locals: { s: @supply }) %>");