config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'faq' => 'pages#faq'
  get 'help' => 'pages#help'

  root 'pages#home'

  resources :notes
  devise_for :teachers
  resources :games
  resources :students
  resources :categories do
    member do
      patch 'update_title'
    end
  end
  resources :questions

  get 'class_gameplay/:id/home' => 'class_gameplay#home', as: :class_gameplay

  get 'student_gameplay/login'
  post 'student_gameplay/login'
  get 'student_gameplay/logout'
  get 'student_gameplay/:id/home/:group_id' =>'student_gameplay#home', as: :student_gameplay

  get 'teacher_gameplay/:id/current_group/:group_id' => 'teacher_gameplay#current_group', as: :current_group
  get 'teacher_gameplay/:id/home' => 'teacher_gameplay#home', as: :teacher_gameplay
  post 'teacher_gameplay/:id/home' => 'teacher_gameplay#home'
  patch 'teacher_gameplay/:id/update_score/:group_id' => 'teacher_gameplay#update_score', as: :update_score
  get 'teacher_gameplay/:id/edit_score/:group_id' => 'teacher_gameplay#edit_score', as: :edit_score
  patch 'teacher_gameplay/:id/next_group' => 'teacher_gameplay#next_group', as: :next_group
  get 'teacher_gameplay/:id/active/:student_id' => 'teacher_gameplay#active', as: :active
  patch 'teacher_gameplay/:id/next_question/:question_id/:group_id' => 'teacher_gameplay#next_question', as: :next_question
  post 'teacher_gameplay/:id/send_message/:group_id' => 'teacher_gameplay#send_message', as: :send_message

  get 'game_sessions/:game_id/new' => 'game_sessions#new', as: :new_game_session
  post 'game_sessions/:game_id/create' => 'game_sessions#create', as: :create_game_session
  get 'game_sessions/:id/groups' => 'game_sessions#groups', as: :game_session_groups
  delete 'game_sessions/:id/destroy' => 'game_sessions#destroy', as: :delete_game_session
  patch 'game_sessions/:id/assign_groups' => 'game_sessions#assign_groups', as: :assign_groups
  post 'game_sessions/:id/add_player/:group_id/:student_id' => 'game_sessions#add_player', as: :add_player
  patch 'game_sessions/:id/end_game' => 'game_sessions#end_game', as: :end_game
  patch 'game_sessions/:id/update_map' => 'game_sessions#update_map'
  get 'game_sessions/:id/add_group' => 'game_sessions#add_group'
  patch 'game_sessions/:id/update' => 'game_sessions#update', as: :update_game_session
  get 'game_sessions/:id/edit' => 'game_sessions#edit', as: :edit_game_session

  post 'supplies/:id/create/:group_id' => 'supplies#create', as: :supply
  get 'supplies/:id/edit/:supply_id' => 'supplies#edit', as: :edit_supply
  patch 'supplies/:id/update/:supply_id' => 'supplies#update', as: :update_supply
  delete 'supplies/:id/destroy/:supply_id' => 'supplies#destroy', as: :delete_supply

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions
  has_many :category_game_session_assignments
  has_many :game_sessions, through: :category_game_session_assignments
  belongs_to :teacher

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :teacher_id, presence: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :update_title]
  before_action :authenticate_teacher!

  def index
    @categories = Category.where(teacher_id: current_teacher.id)
  end

  def show
    @questions = Question.where(category_id: @category.id)
  end

  def new
    @category = Category.create(teacher_id: current_teacher.id,
        name: "Click the pencil to edit title name.")
    Question.create!(category_id: @category.id, content: "Click the pencil to edit
        questions.", difficulty_level: 1, right: 0, wrong: 0)

    redirect_to @category
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    @questions = Question.where(category_id: @category.id)
    respond_to do |format|
      if @category.update(category_params)
        format.js
      else
        format.html { redirect_to @category, notice: 'Category failed to be updated.'}
      end
    end
  end

  def update_title
    respond_to do |format|
      if @category.update(category_params)
        format.js
      else
        format.html { redirect_to @category, notice: 'Category failed to be updated.'}
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.js
    end
  end

  private def set_category
    @category = Category.find(params[:id])
  end

  private def category_params
    params.require(:category).permit(:name, :teacher_id,
        questions_attributes: [:id, :content, :difficulty_level, :right, :wrong, :answer])
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit_title.html.erb
<%= simple_form_for @category, url: update_title_category_path(@category), html: { class: "" }, remote: true do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, label: false, wrapper_html: { class: "mdl-textfield mdl-js-textfield textfield-demo" }, input_html: { class: "mdl-textfield__input text-input" }, label_html: { class: "mdl-textfield__label" } %>

  <divc lass="update-button-wrapper">
    <%= f.button :submit, "Update Title", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
  </div>
<% end %>

app/views/categories/_form.html.erb
<div id="form-container" class="addQuestionsModal mdl-cell mdl-cell--9-col mdl-shadow--4dp">
  <%= simple_form_for @category, html: { class: "" }, remote: true do |f| %>
    <%= f.error_notification %>
    <div id="question-list" class="">
        <%= link_to 'Add <i class="fa fa-plus"></i>'.html_safe, "#", id: "copy_link", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" id="exitAddQuestions">X</button>
      <div id="new-question-form">
        <%= render partial: '/questions/form', locals: { f: f } %>
      </div>
    </div>
    <div>
      <%= f.button :submit, "Submit Questions", id: "submitQuestions", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    </div>
  <% end %>
</div>

app/views/categories/destroy.js.erb
$('#category<%= @category.id %>').remove();

app/views/categories/edit.js.erb
$("#category-name").html("<%= j(render partial: 'edit_title') %>");
$(".text-input").select();

app/views/categories/index.html.erb
<div class="mdl-cell mdl-cell--12-col center">
  <h3>Available Categories</h3>
</div>

<div class="mdl-cell mdl-cell--4-col"></div>

<table class="mdl-cell mdl-cell--4-col mdl-data-table mdl-js-data-table mdl-shadow--4dp">
  <thead>
    <tr>
      <th colspan="2"><%= link_to 'Add Category <i class="fa fa-plus"></i>'.html_safe, new_category_path %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr id="category<%= category.id %>">
        <td class="mdl-data-table__cell--non-numeric"><%= link_to "#{category.name}", category %></td>
        <td><%= link_to '<i class="fa fa-times"></i>'.html_safe, category, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mdl-cell mdl-cell--4-col"></div>

app/views/categories/show.html.erb
<div class="mdl-cell mdl-cell--1-col"></div>
<div class="mdl-cell mdl-cell--10-col">
  <h3 id="category-name">
    <%= @category.name %>
  </h3>
  <h5 id="category-name-edit"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_category_path(@category), remote: true %></h5>
</div>
<div class="mdl-cell mdl-cell--1-col"></div>

<div class="mdl-cell mdl-cell--1-col"></div>
  <div id="question-list-container" class="mdl-cell mdl-cell--10-col">
    <%= render partial: '/questions/index' %>
  </div>
<div class="mdl-cell mdl-cell--1-col"></div>

<div class="mdl-cell mdl-cell--1-col"></div>
<div class="mdl-cell mdl-cell--10-col">
  <button id="show-question-form" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Add Questions</button>
</div>
<div class="mdl-cell mdl-cell--1-col"></div>

<div id="question-form-container">
  <%= render partial: 'form' %>
</div>

app/views/categories/update.js.erb
$("#question-form-container").html("<%= j(render 'form') %>");
$("#question-list-container").html("<%= j(render partial: '/questions/index') %>");

app/views/categories/update_title.js.erb
$("#category-name").html("<%= j(@category.name) %>");